/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TickersRouteImport } from './routes/tickers'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronCollectRouteImport } from './routes/api/public/cron/collect'

const TickersRoute = TickersRouteImport.update({
  id: '/tickers',
  path: '/tickers',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCollectRoute = ApiPublicCronCollectRouteImport.update({
  id: '/api/public/cron/collect',
  path: '/api/public/cron/collect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/facts': typeof FactsRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/signals': typeof SignalsRoute
  '/tickers': typeof TickersRoute
  '/api/public/cron/collect': typeof ApiPublicCronCollectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/facts': typeof FactsRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/signals': typeof SignalsRoute
  '/tickers': typeof TickersRoute
  '/api/public/cron/collect': typeof ApiPublicCronCollectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/facts': typeof FactsRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/signals': typeof SignalsRoute
  '/tickers': typeof TickersRoute
  '/api/public/cron/collect': typeof ApiPublicCronCollectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/facts'
    | '/pipeline'
    | '/portfolio'
    | '/signals'
    | '/tickers'
    | '/api/public/cron/collect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/facts'
    | '/pipeline'
    | '/portfolio'
    | '/signals'
    | '/tickers'
    | '/api/public/cron/collect'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/facts'
    | '/pipeline'
    | '/portfolio'
    | '/signals'
    | '/tickers'
    | '/api/public/cron/collect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRoute
  FactsRoute: typeof FactsRoute
  PipelineRoute: typeof PipelineRoute
  PortfolioRoute: typeof PortfolioRoute
  SignalsRoute: typeof SignalsRoute
  TickersRoute: typeof TickersRoute
  ApiPublicCronCollectRoute: typeof ApiPublicCronCollectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickers': {
      id: '/tickers'
      path: '/tickers'
      fullPath: '/tickers'
      preLoaderRoute: typeof TickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/collect': {
      id: '/api/public/cron/collect'
      path: '/api/public/cron/collect'
      fullPath: '/api/public/cron/collect'
      preLoaderRoute: typeof ApiPublicCronCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRoute,
  FactsRoute: FactsRoute,
  PipelineRoute: PipelineRoute,
  PortfolioRoute: PortfolioRoute,
  SignalsRoute: SignalsRoute,
  TickersRoute: TickersRoute,
  ApiPublicCronCollectRoute: ApiPublicCronCollectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
