/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TickersRouteImport } from './routes/tickers'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DataRouteImport } from './routes/data'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedMyPortfolioRouteImport } from './routes/_authenticated/my-portfolio'
import { Route as ApiPublicCronHourlyRebalanceRouteImport } from './routes/api/public/cron/hourly-rebalance'
import { Route as ApiPublicCronCollectRouteImport } from './routes/api/public/cron/collect'
import { Route as ApiPublicCronBackfillMarketRouteImport } from './routes/api/public/cron/backfill-market'

const TickersRoute = TickersRouteImport.update({
  id: '/tickers',
  path: '/tickers',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPortfolioRoute =
  AuthenticatedMyPortfolioRouteImport.update({
    id: '/my-portfolio',
    path: '/my-portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronHourlyRebalanceRoute =
  ApiPublicCronHourlyRebalanceRouteImport.update({
    id: '/api/public/cron/hourly-rebalance',
    path: '/api/public/cron/hourly-rebalance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCollectRoute = ApiPublicCronCollectRouteImport.update({
  id: '/api/public/cron/collect',
  path: '/api/public/cron/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronBackfillMarketRoute =
  ApiPublicCronBackfillMarketRouteImport.update({
    id: '/api/public/cron/backfill-market',
    path: '/api/public/cron/backfill-market',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/data': typeof DataRoute
  '/documents': typeof DocumentsRoute
  '/facts': typeof FactsRoute
  '/insights': typeof InsightsRoute
  '/pipeline': typeof PipelineRoute
  '/scenarios': typeof ScenariosRoute
  '/signals': typeof SignalsRoute
  '/tickers': typeof TickersRoute
  '/my-portfolio': typeof AuthenticatedMyPortfolioRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/api/public/cron/backfill-market': typeof ApiPublicCronBackfillMarketRoute
  '/api/public/cron/collect': typeof ApiPublicCronCollectRoute
  '/api/public/cron/hourly-rebalance': typeof ApiPublicCronHourlyRebalanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/data': typeof DataRoute
  '/documents': typeof DocumentsRoute
  '/facts': typeof FactsRoute
  '/insights': typeof InsightsRoute
  '/pipeline': typeof PipelineRoute
  '/scenarios': typeof ScenariosRoute
  '/signals': typeof SignalsRoute
  '/tickers': typeof TickersRoute
  '/my-portfolio': typeof AuthenticatedMyPortfolioRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/api/public/cron/backfill-market': typeof ApiPublicCronBackfillMarketRoute
  '/api/public/cron/collect': typeof ApiPublicCronCollectRoute
  '/api/public/cron/hourly-rebalance': typeof ApiPublicCronHourlyRebalanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/data': typeof DataRoute
  '/documents': typeof DocumentsRoute
  '/facts': typeof FactsRoute
  '/insights': typeof InsightsRoute
  '/pipeline': typeof PipelineRoute
  '/scenarios': typeof ScenariosRoute
  '/signals': typeof SignalsRoute
  '/tickers': typeof TickersRoute
  '/_authenticated/my-portfolio': typeof AuthenticatedMyPortfolioRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/api/public/cron/backfill-market': typeof ApiPublicCronBackfillMarketRoute
  '/api/public/cron/collect': typeof ApiPublicCronCollectRoute
  '/api/public/cron/hourly-rebalance': typeof ApiPublicCronHourlyRebalanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/auth'
    | '/data'
    | '/documents'
    | '/facts'
    | '/insights'
    | '/pipeline'
    | '/scenarios'
    | '/signals'
    | '/tickers'
    | '/my-portfolio'
    | '/portfolio'
    | '/api/public/cron/backfill-market'
    | '/api/public/cron/collect'
    | '/api/public/cron/hourly-rebalance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/auth'
    | '/data'
    | '/documents'
    | '/facts'
    | '/insights'
    | '/pipeline'
    | '/scenarios'
    | '/signals'
    | '/tickers'
    | '/my-portfolio'
    | '/portfolio'
    | '/api/public/cron/backfill-market'
    | '/api/public/cron/collect'
    | '/api/public/cron/hourly-rebalance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/actions'
    | '/auth'
    | '/data'
    | '/documents'
    | '/facts'
    | '/insights'
    | '/pipeline'
    | '/scenarios'
    | '/signals'
    | '/tickers'
    | '/_authenticated/my-portfolio'
    | '/_authenticated/portfolio'
    | '/api/public/cron/backfill-market'
    | '/api/public/cron/collect'
    | '/api/public/cron/hourly-rebalance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActionsRoute: typeof ActionsRoute
  AuthRoute: typeof AuthRoute
  DataRoute: typeof DataRoute
  DocumentsRoute: typeof DocumentsRoute
  FactsRoute: typeof FactsRoute
  InsightsRoute: typeof InsightsRoute
  PipelineRoute: typeof PipelineRoute
  ScenariosRoute: typeof ScenariosRoute
  SignalsRoute: typeof SignalsRoute
  TickersRoute: typeof TickersRoute
  ApiPublicCronBackfillMarketRoute: typeof ApiPublicCronBackfillMarketRoute
  ApiPublicCronCollectRoute: typeof ApiPublicCronCollectRoute
  ApiPublicCronHourlyRebalanceRoute: typeof ApiPublicCronHourlyRebalanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickers': {
      id: '/tickers'
      path: '/tickers'
      fullPath: '/tickers'
      preLoaderRoute: typeof TickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-portfolio': {
      id: '/_authenticated/my-portfolio'
      path: '/my-portfolio'
      fullPath: '/my-portfolio'
      preLoaderRoute: typeof AuthenticatedMyPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/hourly-rebalance': {
      id: '/api/public/cron/hourly-rebalance'
      path: '/api/public/cron/hourly-rebalance'
      fullPath: '/api/public/cron/hourly-rebalance'
      preLoaderRoute: typeof ApiPublicCronHourlyRebalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/collect': {
      id: '/api/public/cron/collect'
      path: '/api/public/cron/collect'
      fullPath: '/api/public/cron/collect'
      preLoaderRoute: typeof ApiPublicCronCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/backfill-market': {
      id: '/api/public/cron/backfill-market'
      path: '/api/public/cron/backfill-market'
      fullPath: '/api/public/cron/backfill-market'
      preLoaderRoute: typeof ApiPublicCronBackfillMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyPortfolioRoute: typeof AuthenticatedMyPortfolioRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyPortfolioRoute: AuthenticatedMyPortfolioRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActionsRoute: ActionsRoute,
  AuthRoute: AuthRoute,
  DataRoute: DataRoute,
  DocumentsRoute: DocumentsRoute,
  FactsRoute: FactsRoute,
  InsightsRoute: InsightsRoute,
  PipelineRoute: PipelineRoute,
  ScenariosRoute: ScenariosRoute,
  SignalsRoute: SignalsRoute,
  TickersRoute: TickersRoute,
  ApiPublicCronBackfillMarketRoute: ApiPublicCronBackfillMarketRoute,
  ApiPublicCronCollectRoute: ApiPublicCronCollectRoute,
  ApiPublicCronHourlyRebalanceRoute: ApiPublicCronHourlyRebalanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
